name: outlook-exporter
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  - pywin32

  - pip:
      - streamlit
      - stqdm
      - sqlalchemy
      - bokeh
      - colormath
      - gcsa
      - qrcode
      - sqlalchemy
      - stqdm
      - streamlit
      - python-opencv
